language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: lvEOcQSs1ps3it6LWzYgZ8P5gCYYhsfrTWxIwIYP3id3q9GH9vRDHT+hCsSAV6hljWn9RfJfg0+HraIQuZuyBS3BGuvet35g5TPFNx4F6VtFPLLRQSOgUi+J7lQSUWQHH3Hn5NG0n310m9Liq3kSxXjz7KM304bScWOIKETDXZ/0fgkuMKxDu0UOAZ4oYKu64r08QVI5vl7aMpWQE6FCwV4wXwKGekKkdoTgIfBwYkhB/CwX0Zt09MjfsOALiRqiILoDMxUHzbQ15SUJOteUhUTqkVytDwJriKeCbaEQwfEp1+0Sfos4VnN5um0Nfdc1k8PIenVEcfWVAjNNaHEOA5a+k7xVTTzaiz8I3ZFKpwooEbBDEReXGgNdggFknkvHLXc7cnNoZDWlA6XLAnfcWYdo4nPkm+8LJTQKjaUlM8j3CoPYwUu7yy9rVmWuXyPjHgKVsSPb8E3JMaLrzT5l/ZqpRM3lfQQpIvhNaPb0C9ny5qeeP6fBi0yLcKXapkALXCdc7C/t7jt7nOBiUubSb5/PV+TGYQ4Zq9s86HSurNabNEa82LgL0lJnqq8Z2nucYUpXH2ufSseoairOmoEt5yZ+hexjpwGsp5Ch6mUWzZRJzrrP/Cr4Rxo1RpX+Fr7iptVULplN6KtwJhar8rANLG+Jx0vBUO5VuWR599RbjRc=
  on:
    tags: true
    repo: gadgetmobile/blebox_uniapi
    python: 3.8
