language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: "ht6haChKTgXckxr08rRZ1QTvcEqbQK0YaMD1YzOOq6S1SNtYwJRyaqaqGxSUwe58cQRG7A1KI55JML5syXeGjS8IaX2YdM/RBSdQy6vkNkddiKH8zF44+a5gjUcuQLFqbu3hIlBThP7Xe5dUHppw8m2tsgEVtlnWk/33YAy0Ae6ZOON/LvPKuyLD/rQ2l5nbcItjyHHfbyRCKrUUVw4D+u4WikJjj7Iomc+ByrQJxyEGWqCvTSxIelHn0StVjcrScmW1/JvcisAf8du0ulRJpYnWCGYCkBRaRTAKzQHko7+H9MLYymD3OsBWrORYT+raddVcph59u7qb2gbHmBe4ZF6giFjbvYRxt7z+oL20FHQgJrWnt2e1iE53Sc+Mp5lIzNM08h+o376ySycB9Xmwe0b536qMlG2gSuIzjZ7zNMV144oLHgNnWHfr9XUaY2ehDKe6dVNWdm4WzAjAqEHjuRIYkSoMyKd0/FFBxoHxBp7IjZFzOb0KdzmpxELzPKuI2UARvwALX+52+cUIKtd7FmrH5R6sT3sUSTeYXPPRjUEKL+m8Qe3kUBjnyJsbUbs9w8K+A9jusW11LPCR6jMwkQby92u/OROMm7lfvNlj/zyQsRUN2OQ21Vh6QjpT5PI0w9R1Xc9V2XwS31dYnYVEByisOZ0AjSv/b3GkgvMmhxk="
  on:
    tags: true
    repo: gadgetmobile/blebox_uniapi
    python: 3.8
