language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: xu5unRZkE5IXUH4qzR1j8H4nsNw9sJ0mTuEoBS8Zy1WK9K0sZVzY3sgEY0+hOtI+Vv4hMs6MSr0YgTuiNu4iljeHW+mjPEOrX7Ho8d6g0X49bMOzYQEpOvIilcdMcwRR95SeVBrsmLSr0NF8sDFliWTtj8XgpjNEYDv+2uT2i67SEnH33PzMFIfCoOSf0ue91caldYByE5BfQB90WvHhCvND+BWWSVFPWgK8QZHSXRevkIamVrNLRoO+BKUn+ypphULvAzC1jfFBLVVgPODwiJdk8LB6RCU38rzyIC02/XY02IUIOWmwpgfsjoFXg5oZwZkiOq21KEpmDPGSCUy5fT5z5JZCxx7MHn1nghDVx3s8M+lx7a5JdRU4wdvV3LN76EXq/SEpY3bwg/pRBlb8gPooOwDALNoq11jvOtD6p88waAJogyTj7ga5wcReFJaPqJQuHtCUBpvbskNMoNBaPA5vNXS2puBOb8ASiJWJZQYC7+qpwVEXWk/8kEoqoJQgwO673aWw4YpDaPIgIwf0KHUC87cthtk8B/Nzp0C+O32+JI6KA33C0lQeRgXQ6iQDUSju8iMBmW3R/ffJacKgzY25bGcsznucGeGH7oc4ibvCmDlzlCre9t4ofLcpPgZ6qoJCjYe/pMTnL/spOlo2zodXuD13Z6kudgn6SuhUSnQ=
  on:
    tags: true
    repo: blebox/blebox_uniapi
    python: 3.8
